apiVersion: v1
kind: PersistentVolume
metadata:
  name: sparkrwx
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "<UPDATE_ME>"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkrwx
spec:
  storageClassName: manual
  volumeName: sparkrwx
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi