---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "services", "endpoints", "pods", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: Role
  name: spark
subjects:
  - kind: ServiceAccount
    name: spark