apiVersion: v1
kind: Service
metadata:
  name: local-spark
spec:
  selector:
    spark-app-selector: local-spark
  ports:
    - name: driver-rpc-port
      protocol: TCP 
      port: 7078
      targetPort: 7078
    - name: blockmanager
      protocol: TCP
      port: 7079
      targetPort: 7079